from pprint import pprint
a = [
    'Otabek Karimov',
    'Javohir Abdullayev',
    'Xadicha Norqulova',
    'Madina Komilova',
    'Iskandar Rahmonov',
    'Fotima Ahmedova',
    'Sherzod Omonov',
    'Amir Saidov',
    'Xurshida Raximova',
    'Ravshan Tursunov',
    'Nigora Usmonova',
    'Bekzod Safarov',
    'Sardor Yoldoshev',
    'Asliddin Oripov',
    'Bahodir Bobomurodov',
    'Tohir Mamadaliyev',
    'Muhabbat Xudoyberdiyeva',
    'Kamoliddin Fozilov',
    'Gulnoza Bozorova',
    'Zulfiya Obidova',
    'Sirojiddin Torayev',
    'Dilbar Xalilova',
    'Olim Qodirov',
    'Sevinch Saydullayeva',
    'Zokir Egamberdiyev',
    'Shahzod Norboev',
    'Muhammadbek Mahmudov',
    'Ruhsora Qosimova',
    'Alisher Yusupov',
    'Nasiba Qobilova',
    'Rustam Kenjaboyev',
    'Rahim Hakimov',
    'Shavkat Narziyev',
    'Feruza Tohirova',
    'Mohinur Azimova',
    'Suhrob Rasulov',
    'Dildora Abduraimova',
    'Umarxon Turgunov',
    'Kamol Sharipov',
    'Omina Xolmatova',
    'Habibulloh Saidov',
    'Sarvinoz Abdullayeva',
    'Abdulloh Fayzullayev',
    'Marjona Yoqubova',
    'Farhod Rasulov',
    'Nodir Norqulov',
    'Asilbek Zokirov',
    'Zebo Abdurahmonova',
    'Sherali Ismatov',
    'Abdulaziz Salimov',
    'Gulchehra Vohidova',
    'Muzaffar Ganiyev',
    'Xolida Oktamova',
    'Elyor Rajabov',
    'Mironshoh Axmatov',
    'Sohiba Qochqorova',
    'Shoira Turgunova',
    'Fayzullo Mamatov',
    'Ziyoda Xasanova',
    'Mansur Ergashov',
    'Akmal Abdurahmonov',
    'Karima Usmonova',
    'Dilnoza Salimova',
    'Ravshan Tohirov',
    'Baxtiyor Sobirov',
    'Gulhayo Karimova',
    'Nozima Toraeva',
    'Husan Yusupov',
    'Raxima Rahimova',
    'Dilshod Toxirov',
    'Abdurasul Shamsiyev',
    'Gulchehra Ahmadjonova',
    'Muborak Xoliqova',
    'Diyor Alimov',
    'Dildora Rustamova',
    'Fotima Qudratova',
    'Husniddin Karimov',
    'Madina Jorayeva',
    'Zubayda Ismoilova',
    'Sardor Zokirov',
    'Nigora Xasanova',
    'Azamat Saidov',
    'Zahro Toxtasinova',
    'Sherali Ganiyev',
    'Anora Boltaeva',
    'Zamira Tojiboyeva',
    'Azizbek Umarov',
    'Ulugbek Norqobilov',
    'Alisher Gofurov',
    'Aziza Narziyeva',
    'Jamshid Abdujalilov',
    'Hasan Mahmudov',
    'Habiba Ergasheva'
]



for i in range(len(a)):
    for j in range(i + 1, len(a)):
        if a[i] > a[j]:
            a[i], a[j] = a[j], a[i]
            
pprint(a)